# pool: 'Hosted Ubuntu 1604'
pool: 'Hosted VS2017'

# variables:
# - name: managementGroupId
#   value: root
# - name: blueprintName
#   value: 101-boilerplate
# - name: spnId
#   value: 'a50a4137-5dfa-4fe7-b283-4639e27b2119'
# - name: subscriptionId
#   value: 'd56e652e-758d-480a-8f0d-47f230264b4c'
# - name: tenantId
#   value: '220caee9-352a-4eb3-80eb-cc1dabf7be3c'
# - group: azureLoginDetails

trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

- task: nepeters.azure-blueprints.CreateBlueprint.CreateBlueprint@1
  displayName: 'Create Azure Blueprint'
  inputs:
    azureSubscription: 'pipelines-runner' # this is the service connection
    BlueprintName: '101-boilerplate'
    BlueprintPath: '.\samples\101-blueprint'
    PublishBlueprint: true

