pool: 'Hosted Ubuntu 1604'

variables:
 - name: spnName
   value: 'pipelines-runner'
 - name: blueprintName
   value: 101-boilerplate
 - name: subscriptionId
   value: 'e93d3ee6-fac1-412f-92d6-bfb379e81af2'

trigger:
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .gitignore
    - .github/*

steps:

- task: nepeters.azure-blueprints.CreateBlueprint.CreateBlueprint@1
  displayName: 'Create Azure Blueprint'
  inputs:
    azureSubscription: '$(spnName)' # this is the service connection
    BlueprintName: '$(blueprintName)'
    BlueprintPath: '.\samples\$(blueprintName)'
    PublishBlueprint: true

- task: nepeters.azure-blueprints.AssignBlueprint.AssignBlueprint@1
  displayName: 'Assign Azure Blueprint'
  inputs:
    azureSubscription: '$(spnName)'
    AssignmentName: 'pla-$(blueprintName)' # pla == PipeLinesAssignment
    BlueprintName: '$(blueprintName)'
    ParametersFile: '.\samples\$(blueprintName)\assign\assign.json'
    SubscriptionID: '$(subscriptionId)'
    Wait: true
    # version not specified because it defaults to latest